---
title: "Group 02 CA pollution burden"
author: "Elmera Azadpour & Annie Lovell"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

#### a. read in the CalEnviroScreen data 
```{r}
ces <- read_csv(here("data","ces3demographics.csv")) %>% clean_names()
```



```{r}
ggplot(data = ces, aes(x = white_percent, y=ces_3_0_score)) + 
         geom_hex() +
  labs(x = "% White",
       y = "CalEnviroScreen pollution burden score",
       title = "% White Population vs CalEnviroScreen pollution burden score") +
  scale_fill_gradient(low = "navy", high = "orange") +
  theme_minimal()
```
Figure 1:  This figure shows that as the percentrage of white people in a population increases, the pollution burden score decreases, and the the count of people at the lower pollution burden scores is greater.  For lower percent white population there are higher counts at higher pollution burden scores.  


